### ISSUE TITLE
Crashes when IOException issued

### ISSUE THREAD

**Issue by ys8lcc** [luthfihariz/news-reader-clean#1]
The app will be forced to close when there is no internet connection. I have found the solution to this issue.

Replace these lines of code in Presenter
        .subscribeOn(mScheduler.io())
                .observeOn(mScheduler.ui())
                .doOnNext(this::showArticles)
                .doOnError(this::showErrorView)
                .subscribe();

With
                .observeOn(mScheduler.ui())
                .subscribeOn(mScheduler.io())
                .subscribe(this::showArticles, this::showErrorView);

I hope it will be helpful.
Respect.

**Comment by luthfihariz** [comment]
Thank you, will work on this.

**Comment by luthfihariz** [comment]
It has been fixed. Thank you.
